[[project]]
name = "Verso"
desc = "An innovative web browser with privacy and security focus"
tags = ["servo", "rust"]
links = [
    { name = "homepage", url = "/verso" },
    { name = "github", url = "https://github.com/versotile-org/verso" },
    { name = "docs", url = "https://docs.versotile.org/verso" },
]

[[project]]
name = "FORTRESS"
desc = "Security Container for Sensitive Data"
tags = ["vault", "encryption", "cryptography", "security", "isolation"]


links = [
    { name = "homepage", url = "/fortress" },
    { name = "github", url = "https://github.com/versotile-org/fortress" },
    { name = "docs", url = "https://docs.versotile.org/fortress" },
]


